version: "3.9"

services:
  db:
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    environment:
      POSTGRES_USER: gov
      POSTGRES_PASSWORD: govpass
      POSTGRES_DB: gov_minutes
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "gov"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      DATABASE_URL: postgresql+psycopg2://gov:govpass@db:5432/gov_minutes
      EMBEDDING_PROVIDER: local
      EMBEDDING_MODEL: local-hash
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:

